version: '3'
services:
  slackdrive:
    build: .
    image: slackdrive
    volumes:
      - ./index.js:/slack-drive/index.js
      - ./package.json:/slack-drive/package.json
      - ./config.json:/slack-drive/config.json
      - ./client_secret.json:/etc/cloud/client_secret.json
      - ./dist:/var/data
