#!/bin/bash

if [ $# -eq 0 ]; then
  deploy drive-redirect
  deploy event-consumer
  deploy event-listener
  deploy slash-command

elif [ "$1" == "drive-redirect" ]; then
  cd $1
  npm install --save
  functions deploy redirect --trigger-http --timeout 3s

elif [ "$1" == "event-listener" ]; then
  cd $1
  npm install --save
  functions deploy publishEvent --trigger-http --timeout 3s

elif [ "$1" == "event-consumer" ]; then
  cd $1
  npm install --save
  functions deploy consumeEvent --trigger-topic=${SLACK_EVENTS_TOPIC}

elif [ "$1" == "slash-command" ]; then
  cd $1
  npm install --save
  functions deploy slashCommand --trigger-http --timeout 3s

else
  echo "Usage: deploy [event-listener|event-consumer|redirect|slash-command]"
  exit 1
fi
