#!/bin/bash

if [ $# -eq 0 ]; then
  deploy event-listener
  deploy consumer
  deploy messenger

elif [ "$1" == "event-listener" ]; then
  cd $1
  npm install --save
  functions deploy publishEvent --trigger-http --timeout 3s

elif [ "$1" == "consumer" ]; then
  cd $1
  npm install --save
  functions deploy consumeEvent --trigger-topic=${SLACK_EVENTS_TOPIC}

elif [ "$1" == "messenger" ]; then
  cd $1
  npm install --save
  functions deploy subscribe --trigger-topic=${SLACK_MESSAGES_TOPIC}

else
  echo "Usage: deploy [event-listener|consumer|messenger]"
  exit 1
fi
